[workspace]
resolver = "2"

members = [
    "infrastructure",
    "command/domain",
    "command/processor",
    "command/interface-adaptor",
    "command/write-api-server",
    "read-model-updater",
    "query/processor",
    "query/interface-adaptor",
    "query/read-api-server",
]