[workspace]

members = [
    "infrastructure",
    "command/domain",
    "command/processor",
    "command/interface-adaptor",
    "command/write-api-server",
    "rmu",
    "query/processor",
    "query/interface-adaptor",
    "query/read-api-server",
    # "query/refinery"
]
