environments:
  '{{ .Environment.Name }}':
    values:
      - '../../config/environments/{{ .Environment.Name }}.yaml'
---
releases:
  - name: write-api-server
    namespace: '{{ .Namespace | default "ceer" }}'
    labels:
      subsystem: write-api
      group: write-api-server
    chart: ../../charts/write-api-server
    version: '{{ .Values.writeApi.writeApiServer.version }}'
    installedTemplate: '{{ .Values.writeApi.writeApiServer.enabled }}'
    values:
      - values/settings.yaml.gotmpl