{{- if .Values.service.enabled }}
{{- $svcType := .Values.service.type }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "write-api-server.fullname" . }}
  labels:
    {{- include "write-api-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $i, $v := .Values.service.ports }}
    - targetPort: {{ $v.targetPort }}
      name: "{{ $v.name }}"
      port: {{ $v.port }}
      {{- if and (eq $svcType "NodePort") $v.nodePort }}
      nodePort: {{ $v.nodePort }}
      {{- end }}
      protocol: "{{ $v.protocol }}"
    {{- end }}
  selector:
    {{- include "write-api-server.selectorLabels" . | nindent 4 }}
{{- end }}