# WIP
version: '3.6'
services:
  write-api-server-1:
    image: j5ik2o/cqrs-es-example-rs-write-api-server:latest-arm64
    container_name: write-api-server-1
    ports:
      - 18080:8080
    environment:
      AWS_REGION: ap-northeast-1
      RUST_BACKTRACE: full
      APP__API__HOST: "0.0.0.0"
      APP__API__PORT: 8080
      APP__PERSISTENCE__JOURNAL_TABLE_NAME: journal
      APP__PERSISTENCE__JOURNAL_AID_INDEX_NAME: journal-aid-index
      APP__PERSISTENCE__SNAPSHOT_TABLE_NAME: snapshot
      APP__PERSISTENCE__SNAPSHOT_AID_INDEX_NAME: snapshot-aid-index
      APP__PERSISTENCE__JOURNAL_SHARD_COUNT: 64
      APP__AWS__REGION_NAME: ${AWS_REGION}
      APP__AWS__ENDPOINT_URL: http://localstack:4566
      APP__AWS__ACCESS_KEY_ID: x
      APP__AWS__SECRET_ACCESS_KEY: x
    #volumes:
    #  - ../../config:/config
    depends_on:
      - localstack
      - dynamodb-admin
      - dynamodb-setup
#  read-model-updater-1:
#    image: j5ik2o/cqrs-es-example-rs-read-model-updater:latest-arm64
#    container_name: read-model-updater-1
#    ports:
#      - 18081:8080
#    environment:
#      AWS_REGION: ap-northeast-1
#      RUST_BACKTRACE: full
#      APP__API__HOST: "0.0.0.0"
#      APP__API__PORT: 8080
#      APP__AWS__REGION_NAME: ${AWS_REGION}
#      APP__AWS__ENDPOINT_URL: http://localstack:4566
#      APP__AWS__ACCESS_KEY_ID: x
#      APP__AWS__SECRET_ACCESS_KEY: x
#      APP__RMU__STREAM_ARN: ${APP__RMU__STREAM_ARN- }
#      APP__RMU__MAX_ITEM_COUNT: 32
#    #volumes:
#    #  - ../../config:/config
#    depends_on:
#      - localstack
#      - dynamodb-admin
#      - dynamodb-setup
#  read-api-server-1:
#    image: cqrs-es-example-rs-read-api-server
#    container_name: read-api-server-1
#    entrypoint: [ "/opt/docker/bin/adceet-read-api-server", "-e", "development" ]
#    ports:
#      - 18084:8081
#    environment:
#      AWS_REGION: ap-northeast-1
#      AWS_ACCESS_KEY_ID: x
#      AWS_SECRET_ACCESS_KEY: x
#      DB_URL: jdbc:mysql://mysql-local/adceet?allowPublicKeyRetrieval=true&useSSL=false
#      DB_USER: adceet
#      DB_PASSWORD: adceet
#    depends_on:
#      - mysql
#      - flyway
#      - write-api-server-1
#      - write-api-server-2
#      - write-api-server-3
#      - read-model-updater-1
