version: '3.6'
services:
  write-api-server-1:
    image: cqrs-es-example-rs-write-api-server
    container_name: write-api-server-1
    build:
      context: ../../
      dockerfile: command/write-api/Dockerfile
    ports:
      - 18080:8080
    environment:
      AWS_REGION: ap-northeast-1
    depends_on:
      - dynamodb-local
      - dynamodb-admin
      - dynamodb-setup
#  read-api-server-1:
#    image: cqrs-es-example-rs-read-api-server
#    container_name: read-api-server-1
#    entrypoint: [ "/opt/docker/bin/adceet-read-api-server", "-e", "development" ]
#    ports:
#      - 18084:8081
#    environment:
#      AWS_REGION: ap-northeast-1
#      AWS_ACCESS_KEY_ID: x
#      AWS_SECRET_ACCESS_KEY: x
#      DB_URL: jdbc:mysql://mysql-local/adceet?allowPublicKeyRetrieval=true&useSSL=false
#      DB_USER: adceet
#      DB_PASSWORD: adceet
#    depends_on:
#      - mysql
#      - flyway
#      - write-api-server-1
#      - write-api-server-2
#      - write-api-server-3
#      - read-model-updater-1
