[api]
host = "0.0.0.0"
port = 8080

[aws]
region_name = "ap-northeast-1"
endpoint_url = "http://localhost:4566"
access_key_id = "x"
secret_access_key = "x"

[rmu]
stream_arn = "arn:aws:iam::000000000000:role/lambda-r1"
max_item_size = 100