[api]
host = "0.0.0.0"
port = 8080

[aws]
region_name = "ap-northeast-1"
endpoint_url = "http://localhost:4566"
access_key_id = "x"
secret_access_key = "x"

[rmu]
stream_arn = "arn:aws:dynamodb:ap-northeast-1:000000000000:table/journal/stream/2023-07-10T05:45:04.275"
max_item_count = 100
